default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: amauri
  password: Deus


development:
  <<: *default
  database: InformationNews_development
  reconnect: true
 
test:
  <<: *default
  database: InformationNews_test

production:
  <<: *default
  database: InformationNews_production
  pool: 15
  reconnect: true